import chalk from 'chalk';
import ora from 'ora';
import { promises as fs } from 'fs';
import { join } from 'path';
import inquirer from 'inquirer';

export async function initPlugin(name: string) {
  const spinner = ora('Initializing plugin...').start();
  
  try {
    const pluginsDir = join(process.env.HOME || process.env.USERPROFILE || '', '.jarvis', 'plugins');
    const pluginDir = join(pluginsDir, name);
    
    // Create plugin directory
    await fs.mkdir(pluginDir, { recursive: true });
    
    // Create plugin template
    const pluginTemplate = `/**
 * Jarvis Plugin: ${name}
 * Generated by Jarvis CLI
 */

module.exports = {
  name: '${name}',
  version: '1.0.0',
  description: 'TODO: Add description',
  
  // Called when plugin is loaded
  async init(jarvis) {
    console.log('Plugin ${name} loaded!');
  },
  
  // Register your commands here
  async register(jarvis) {
    // Example: jarvis.addCommand('my-command', async (args) => { ... })
  }
};
`;
    
    await fs.writeFile(join(pluginDir, 'index.js'), pluginTemplate);
    
    // Create package.json
    const packageJson = {
      name: `jarvis-plugin-${name}`,
      version: '1.0.0',
      description: `Jarvis plugin: ${name}`,
      main: 'index.js',
      keywords: ['jarvis', 'plugin'],
      author: '',
      license: 'MIT'
    };
    
    await fs.writeFile(join(pluginDir, 'package.json'), JSON.stringify(packageJson, null, 2));
    
    // Create README
    const readme = `# ${name} Plugin

A Jarvis plugin.

## Installation

\`\`\`bash
# Plugin is already in your plugins directory
# Enable it in ~/.jarvis/config.json
\`\`\`

## Usage

\`\`\`bash
jarvis <plugin-command>
\`\`\`

## Development

Edit \`index.js\` to add your custom commands.
`;
    
    await fs.writeFile(join(pluginDir, 'README.md'), readme);
    
    spinner.succeed(chalk.green(`Plugin '${name}' created!`));
    console.log(chalk.cyan(`\n📦 Plugin location: ${pluginDir}\n`));
    console.log(chalk.gray('Edit index.js to add your custom commands.\n'));
    
  } catch (error) {
    spinner.fail(chalk.red('Error: ' + (error as Error).message));
  }
}
